# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/ip/Frame_Buffer/Frame_Buffer.xci
# IP: The module: 'Frame_Buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/ip/Frame_Buffer/Frame_Buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Frame_Buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/ip/Frame_Buffer/Frame_Buffer.xci
# IP: The module: 'Frame_Buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/ip/Frame_Buffer/Frame_Buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Frame_Buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
