# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.cache/wt [current_project]
set_property parent.project_path C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet c:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/ip/Frame_Buffer/Frame_Buffer.dcp
set_property used_in_implementation false [get_files c:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/ip/Frame_Buffer/Frame_Buffer.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/Microphone/DPRAM.v
  {C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/OV7670 VGA Camera/OV7670_Registers.v}
  {C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/OV7670 VGA Camera/I2C_Controller.v}
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/Keyboard/debouncer.v
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/Microphone/Audio_Generator.v
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/Keyboard/PWM_RGB.v
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/Keyboard/Buffer_Generator.v
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/Common/Clock_Divider.v
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/Common/sevensegment.v
  {C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/OV7670 VGA Camera/OV7670_Frame_Collector.v}
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/Keyboard/Converter.v
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/Keyboard/keyboard.v
  {C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/OV7670 VGA Camera/OV7670_Controller.v}
  {C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/OV7670 VGA Camera/VGA_Controller.v}
  {C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/OV7670 VGA Camera/Color_Filter.v}
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/Common/debounce.v
  C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/sources_1/imports/Source/nexys4fpga.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/constrs_1/imports/Constraints/Nexys4DDR_C.xdc
set_property used_in_implementation false [get_files C:/Users/Thanh/Desktop/Summer2017_Project/Summer2017_Project.srcs/constrs_1/imports/Constraints/Nexys4DDR_C.xdc]


synth_design -top nexys4fpga -part xc7a100tcsg324-1


write_checkpoint -force -noxdef nexys4fpga.dcp

catch { report_utilization -file nexys4fpga_utilization_synth.rpt -pb nexys4fpga_utilization_synth.pb }
